### ISSUE TITLE
使用 Chrome 远程调试 Android 设备,ubuntu12.04问题?

### ISSUE THREAD

**Issue by chenweihan** [CN-Chrome-DevTools/CN-Chrome-DevTools#32]
看了你使用 Chrome 远程调试 Android 设备文章

本机ubuntu12.04  chrome本机版本 41.0.2272.76
测试设备 红米  

下面是输出;
Devices

Discover USB devices
Port forwarding...
2014011
#JRAEYHYTRGQSGEPN
Chrome (40.0.2214.109)
Open

百度一下
http://www.baidu.com/
inspectfocus tabreloadclose

Nudistfriends
http://www.nffnew.com/?dev#myProfile/whole
inspectfocus tabreloadclose

open,focustab,reload,close 一切正常,就是inspectfocus打开是空白.

难道是我设备问题??

**Comment by chenweihan** [comment]
我换了其他android设备,一样的情况.难道是ubuntu12.04系统原因?

**Comment by yujiangshui** [comment]
点击 inspect 之后，应该跳出那个页面的 DevTools 工具。

能读取到并显示出来，说明你手机的驱动没问题，Chrome 功能也OK，但是 inspect 空白就比较奇葩了。

我的测试机也是红米，在 Mac 下 40.0.2214.115  手机 Chrome 34 是 OK 的。你要不换下别人系统之类的试下？

**Comment by DennisLi87** [comment]
据说白板是需要翻墙，你翻墙试试

**Comment by chenweihan** [comment]
ubuntu下我已经解决了，１是需要翻墙　２是chrome非dev版本，默认没有Devices该功能入口。
可以手动输入chrome://inspect/, 调出Devices，即可正常使用。

**Comment by chenweihan** [comment]
解决了很久，忘记来mark了。呵呵，需要分享的。

**Comment by yujiangshui** [comment]
OK，解决了就 close 了。@chenweihan
