### ISSUE TITLE
readme.md里面高亮正在翻译的

### ISSUE THREAD

**Issue by shuizhongyueming** [CN-Chrome-DevTools/CN-Chrome-DevTools#39]
能不能在readme.md里面高亮那些正在翻译中的文章，这样，想一起参与翻译的时候，不用担心跟其他人翻译重复了

**Comment by SunLn** [comment]
+ JavaScript Memory Profiling
+ Keyboard Shortcuts
+ Authoring and Development Workflow
+ Mobile Emulation
+ Editing Styles And The DOM

还有现在几个未关闭的 PR。都是有在翻译的。

**Comment by shuizhongyueming** [comment]
恩，好像readme.md里面是早就有了，没看到...
