### ISSUE TITLE
Http status code icon

### ISSUE THREAD

**Issue by yakiler** [CN-Chrome-DevTools/CN-Chrome-DevTools#57]
When we open the developer tool, we can see that there are some icons in front of the http status code in the network panel. For example, there are green solid circles and gray hollow circles in front of 200.
I am wondering why there are multiple icons for the same status code. What do they mean?
I am sorry to ask you for help here, I really need help. Thank you

**Comment by stone-freedom** [comment]
gray hollow circles mean that the items were fulfilled directly from your browser cache, meaning that the original requests for the items were returned with headers indicating that the browser could cache them (e.g. future-dated Expires or Cache-Control: max-age headers), and that at the time you triggered the new request, those cached objects were still stored in local cache and had not yet expired.

green solid circles meat that  the response contains a payload that represents the status of the requested resource.
